### PR TITLE
Add geometry msgs

### PR DESCRIPTION
**Pull request by maxsvetlik**
This adds common message support for `geometry_msgs` including `PoseStamped`, `Point`, `Quaternion`, `PoseWithCovaraiance`, `PoseWithCovarianceStamped`, `Twist`, `TwistWithCovariance`, `TwistWithCovarianceStamped` and `Odometry`

### CODE REVIEW

**Comment by maxsvetlik** [comment]
Pending testing after resolving merge conflicts from `main`.

**Review by kvsikand — COMMENTED** [review]
Hmm, so in theory this `robofleet_client_lib` module was broken out to be independent of ROS, so that consumers don't need to have ROS running to use this library. While this PR doesn't change that, it *does* sort of imply that the consumer is using ROS on its own side...

If you look in the base **robofleet_client** repo, there are definitions of these same message types there, which actually uses the ros types
https://github.com/ut-amrl/robofleet_client/blob/master/src/decode_ros.hpp

I'm assuming this change is to enable some other use case...maybe we should chat about what that is?

**Comment by maxsvetlik** [comment]
So I agree that it is redundant with `robofleet_client` but for other clients that depend on `robofleet_client_lib`, they cannot see or utilize these definitions. It feels cleaner to just create generic, non-flatbuffer structs for minimal C++ clients that encompass the entirety of the subscribed & received messages. 

I guess really what I'm suggesting from an software engineering standpoint would be to break out all the structs and templates from `robofleet_client/decode_ros.cpp` and put them in this library so all clients can utilize them for ROS messages, increasing generality.

**Comment by maxsvetlik** [comment]
The specific use case is for the Hololens Unreal robofleet client, where ROS messages are in fact being subscribed to... even though ROS is not installed or depended on directly. So the message fields get stripped from the flatbuffer structs and used in the Hololens data pipeline.

**Review by kvsikand — APPROVED** [review]
This argument works for me!

**Comment by maxsvetlik** [comment]
Compiled and tested as of `1370698`. Merging.

**Pull request merged**
